---
- name: Instance Creation
  os_server:
    cloud: openstack
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_groups }}"
    meta: "{{ item.value.meta }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    userdata: "{{ item.value.userdata}}"
  with_dict: "{{ osp_server_vars }}"

- name: Create IP
  os_floating_ip:
    cloud: openstack
    state: "{{ item.value.state }}"
    reuse: "{{ item.value.reuse }}"
    server: "{{ item.value.name }}"
    network: "{{ item.value.network }}"
    wait: true
    timeout: 200
  with_dict: "{{ osp_server_vars }}"
